[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NITRO_PRESET = "netlify"
  NODE_VERSION = "20"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 8888
  publish = ".output/public"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
